const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.CV_BoundedDragnDrop,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Text,
		C3.Plugins.Button,
		C3.Plugins.AJAX,
		C3.Plugins.Date,
		C3.Plugins.Browser,
		C3.Plugins.TextBox,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.CV_BoundedDragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.AJAX.Acts.Post,
		C3.ScriptsInEvents.Maingame_Event10_Act4,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.LocalStorage.Acts.ClearStorage,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.ScriptsInEvents.Mainmenu_Event9_Act2,
		C3.Plugins.TextBox.Exps.Text,
		C3.ScriptsInEvents.Mainmenu_Event9_Act6,
		C3.ScriptsInEvents.Mainmenu_Event10_Act2,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.ScriptsInEvents.Mainmenu_Event14_Act2,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Manhole: 0},
	{TrashBin: 0},
	{Background: 0},
	{Jump: 0},
	{BoundedDragDrop: 0},
	{Tween: 0},
	{Cat: 0},
	{BGTrigger: 0},
	{ObstacleTrigger: 0},
	{DragDrop: 0},
	{Sprite3: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{ScoreText: 0},
	{Button: 0},
	{AJAX: 0},
	{Date: 0},
	{Browser: 0},
	{MainMenuPage: 0},
	{StartMenuText: 0},
	{BGFade: 0},
	{BGFrame: 0},
	{RegisterButton: 0},
	{TextNama: 0},
	{TextKontak: 0},
	{TextEvent: 0},
	{RegButton: 0},
	{BGFrameSCORE: 0},
	{RestartButton: 0},
	{Frame: 0},
	{Obstacles: 0},
	{MandatoryInput: 0},
	{Score: 0},
	{Speed: 0},
	{GameStart: 0},
	{CreateObjInterval: 0},
	{IDtoogle: 0},
	{UserID: 0},
	{UserName: 0},
	{TimeStamp: 0},
	{Contact: 0},
	{EventLoc: 0},
	{Event: 0}
];

self.InstanceType = {
	Manhole: class extends self.ISpriteInstance {},
	TrashBin: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Cat: class extends self.ISpriteInstance {},
	BGTrigger: class extends self.ISpriteInstance {},
	ObstacleTrigger: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	ScoreText: class extends self.ITextInstance {},
	Button: class extends self.IButtonInstance {},
	AJAX: class extends self.IInstance {},
	Date: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	MainMenuPage: class extends self.ISpriteInstance {},
	StartMenuText: class extends self.ITextInstance {},
	BGFade: class extends self.ISpriteInstance {},
	BGFrame: class extends self.ISpriteInstance {},
	RegisterButton: class extends self.ISpriteInstance {},
	TextNama: class extends self.ITextInputInstance {},
	TextKontak: class extends self.ITextInputInstance {},
	TextEvent: class extends self.ITextInputInstance {},
	RegButton: class extends self.IButtonInstance {},
	BGFrameSCORE: class extends self.ISpriteInstance {},
	RestartButton: class extends self.ISpriteInstance {},
	Frame: class extends self.ISpriteInstance {},
	Obstacles: class extends self.ISpriteInstance {},
	MandatoryInput: class extends self.ITextInputInstance {}
}